/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BookingSubmission {
    serviceType: string;
    description: string;
    userEmail: string;
    dateTime: string;
    timestamp: Time;
}
export type BookingId = string;
export type Time = bigint;
export interface Booking {
    serviceType: string;
    bookingId: BookingId;
    description: string;
    userEmail: string;
    dateTime: string;
    status: string;
    timestamp: Time;
}
export interface backendInterface {
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    submitBooking(submission: BookingSubmission): Promise<void>;
    registerUser(email: string, passwordHash: string): Promise<{ ok: null } | { err: string }>;
    authenticateUser(email: string, passwordHash: string): Promise<{ ok: string } | { err: string }>;
    registerAdmin(email: string, passwordHash: string): Promise<{ ok: null } | { err: string }>;
    getTechnicianBookings(): Promise<Array<Booking>>;
    updateBookingStatus(bookingId: string, status: string): Promise<{ ok: null } | { err: string }>;
    getBookingsAuthenticated(email: string, passwordHash: string): Promise<{ ok: Array<Booking> } | { err: string }>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor._initializeAccessControlWithSecret(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor._initializeAccessControlWithSecret(arg0);
        }
    }
    async submitBooking(arg0: BookingSubmission): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.submitBooking(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.submitBooking(arg0);
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<{ ok: null } | { err: string }> {
        if (this.processError) {
            try {
                return await this.actor.registerUser(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.registerUser(arg0, arg1);
        }
    }
    async authenticateUser(arg0: string, arg1: string): Promise<{ ok: string } | { err: string }> {
        if (this.processError) {
            try {
                return await this.actor.authenticateUser(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.authenticateUser(arg0, arg1);
        }
    }
    async registerAdmin(arg0: string, arg1: string): Promise<{ ok: null } | { err: string }> {
        if (this.processError) {
            try {
                return await this.actor.registerAdmin(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.registerAdmin(arg0, arg1);
        }
    }
    async getTechnicianBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                return await this.actor.getTechnicianBookings();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getTechnicianBookings();
        }
    }
    async updateBookingStatus(arg0: string, arg1: string): Promise<{ ok: null } | { err: string }> {
        if (this.processError) {
            try {
                return await this.actor.updateBookingStatus(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.updateBookingStatus(arg0, arg1);
        }
    }
    async getBookingsAuthenticated(arg0: string, arg1: string): Promise<{ ok: Array<Booking> } | { err: string }> {
        if (this.processError) {
            try {
                return await this.actor.getBookingsAuthenticated(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getBookingsAuthenticated(arg0, arg1);
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
